import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import cn from 'classnames';
import { createTheme, MantineProvider } from '@mantine/core';

import '@mantine/core/styles.css';
import '../styles/global.css';

const inter = Inter({ subsets: ['latin'] });

const theme = createTheme({});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <MantineProvider theme={theme}>
        <body className={cn(inter.className, 'bg-soft-grey')}>{children}</body>
      </MantineProvider>
    </html>
  );
}
