import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { createTheme, MantineProvider, ColorSchemeScript } from '@mantine/core';

import '@mantine/core/styles.css';
import '../styles/global.css';

const inter = Inter({ subsets: ['latin'] });

const theme = createTheme({});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <MantineProvider theme={theme}>
      <html lang="en">
        <head>
          <ColorSchemeScript />
        </head>
        <body className={inter.className}>{children}</body>
      </html>
    </MantineProvider>
  );
}
